apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedelogo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: /metrics
      #   prometheus.io/port: "80"
    spec:
      containers:
        - name: pedelogo-app
          image: kubedevio/pedelogo-catalogo:v1.0.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: pedelogo-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8082
      targetPort: 80
  type: ClusterIP
