apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedelogo-mongodb-app
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:     
      labels:
        app: mongodb
        monitoring: enabled
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        env:        
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd
      # - name: mongodbexporter
      #   image: fabricioveronez/mongo_exporter
      #   ports: 
      #     - containerPort: 9216
      #   env:
      #     - name: MONGODB_URI
      #       value: mongodb://mongouser:mongopwd@localhost:27017  
---

apiVersion: v1
kind: Service
metadata:
  name: pedelogo-mongodb-service
spec:
  selector:
    app: mongodb
    monitoring: enabled
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
